Add override labeling for go-apidiff (#2565)
Signed-off-by: Todd Short <tshort@redhat.com>

diff --git a/.github/workflows/go-apidiff.yaml b/.github/workflows/go-apidiff.yaml
--- a/.github/workflows/go-apidiff.yaml
+++ b/.github/workflows/go-apidiff.yaml
@@ -16,3 +16,22 @@ jobs:
         go-version-file: go.mod
 
     - uses: joelanford/go-apidiff@main
+      id: check-api
+      continue-on-error: true
+
+    - name: Check for override label
+      if: ${{ steps.check-api.outcome == 'failure' }}
+      run: |
+        if gh api repos/$OWNER/$REPO/pulls/$PR --jq '.labels.[].name' | grep -q "${OVERRIDE_LABEL}"; then
+          echo "Found ${OVERRIDE_LABEL} label, overriding failed results."
+          exit 0
+        else
+          echo "No ${OVERRIDE_LABEL} label found, failing the job."
+          exit 1
+        fi
+      env:
+        GH_TOKEN: ${{ github.token }}
+        OWNER: ${{ github.repository_owner }}
+        REPO: ${{ github.event.repository.name }}
+        PR: ${{ github.event.pull_request.number }}
+        OVERRIDE_LABEL: "go-apidiff-override"
